# Generated by Django 3.0.2 on 2020-01-05 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_System', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(blank=True, max_length=30, null=True)),
                ('IP_address', models.CharField(max_length=30, unique=True)),
                ('Mac_address', models.CharField(max_length=30, unique=True)),
                ('Users_name', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(max_length=30)),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase Date(mm/dd/yy)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.OperatingSystem')),
            ],
        ),
    ]
